name: next_photo
description: A Flutter blog application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.3+3

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  freezed: ^2.5.2
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  like_button: ^2.0.5
  logger: ^2.3.0
  photo_view: ^0.15.0
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  timeago: ^3.6.1

dev_dependencies:
  build_runner: ^2.4.10
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  index_generator: ^3.4.1
  integration_test:
    sdk: flutter
  intl_utils: ^2.8.4
  json_serializable: ^6.8.0
  lint: ^2.3.0
  mocktail: ^1.0.3
  mocktail_image_network: ^1.1.0
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

flutter_intl:
  enabled: true
  arb_dir: translations
  output_dir: lib/common/localization/generated

index_generator:
  exclude:
    - '**.g.dart'
    - '**.freezed.dart'
    - '**/blocs/**_event.dart'
    - '**/blocs/**_state.dart'
    - '**/cubits/**_state.dart'
  indexes:
    - path: lib/base
      include:
        - '**'
      name: base
      library: base

    - path: lib/common
      include:
        - '**'
      exclude:
        - 'presentation/localization/generated/**'
        - 'data/http/adapter/unsupported.dart'
        - 'data/http/adapter/mobile_adapter.dart'
        - 'data/http/adapter/web_adapter.dart'
      name: common
      library: common
